name: Github Pages CICD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        if: env.ACT != 'true'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: env.ACT != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error

      - name: Local Artifact Simulation
        if: env.ACT == 'true'
        run: |
          echo "Simulating artifact upload for local testing"
          # Add any necessary local artifact simulation steps here

      - name: Deploy to GitHub Pages
        if: env.ACT != 'true'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Local Deployment Simulation
        if: env.ACT == 'true'
        run: |
          echo "Simulating deployment for local testing"
          # Add any local deployment simulation steps here