name: Github Pages CICD Pipeline

on:
  pull_request:
    types:
      - closed

jobs:
  deploy_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-
      - name: Install dependencies
        run: npm install

      - name: deploy_code
        run: npm run deploy